package header

// Headers in canonical format
const (
	AcceptEncoding                = "Accept-Encoding"
	AccessControlAllowCredentials = "Access-Control-Allow-Credentials"
	AccessControlAllowHeaders     = "Access-Control-Allow-Headers"
	AccessControlAllowMethods     = "Access-Control-Allow-Methods"
	AccessControlAllowOrigin      = "Access-Control-Allow-Origin"
	AccessControlExposeHeaders    = "Access-Control-Expose-Headers"
	AccessControlMaxAge           = "Access-Control-Max-Age"
	AccessControlRequestHeaders   = "Access-Control-Request-Headers"
	AccessControlRequestMethod    = "Access-Control-Request-Method"
	Authorization                 = "Authorization"
	ContentEncoding               = "Content-Encoding"
	ContentLength                 = "Content-Length"
	ContentType                   = "Content-Type"
	Origin                        = "Origin"
	RetryAfter                    = "Retry-After"
	SecWebsocketKey               = "Sec-Websocket-Key"
	StrictTransportSecurity       = "Strict-Transport-Security"
	Upgrade                       = "Upgrade"
	Vary                          = "Vary"
	WWWAuthenticate               = "Www-Authenticate"
	XForwardedFor                 = "X-Forwarded-For"
	XForwardedHost                = "X-Forwarded-Host"
	XForwardedMethod              = "X-Forwarded-Method"
	XForwardedProto               = "X-Forwarded-Proto"
	XForwardedURI                 = "X-Forwarded-Uri"
	XRealIP                       = "X-Real-Ip"
	XRequestID                    = "X-Request-Id"
)
